---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 10m
  releaseName: kube-prometheus-stack
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      chart: kube-prometheus-stack
      version: 65.2.0
      interval: 30m
  values:
    grafana:
      enabled: false
    alertmanager:
      enabled: false
    prometheus:
      prometheusSpec:
        serviceMonitorSelectorNilUsesHelmValues: false
