---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: postgres
spec:
  interval: 10m
  releaseName: postgresql
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      chart: postgresql
      version: 16.0.3
      interval: 30m
  values:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
