---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  url: https://charts.bitnami.com/bitnami
  interval: 10m
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami-pre-2022
  namespace: flux-system
spec:
  url: https://raw.githubusercontent.com/bitnami/charts/pre-2022/bitnami
  interval: 60m
